name: reading_tracker_app
description: "Paperback Reader client app for Android, Web, Windows, and Linux."
publish_to: "none"
version: 1.7.0+362

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  path: ^1.9.0
  http: ^1.2.2
  intl: ^0.20.3
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  google_fonts: ^8.2.1
  dynamic_color: ^1.7.0
  flutter_displaymode: ^0.7.0
  window_manager: ^0.5.2
  package_info_plus: ^10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  adaptive_icon_background: "assets/android-icon-background.png"
  adaptive_icon_foreground: "assets/android-icon-foreground.png"
  adaptive_icon_monochrome: "assets/android-icon-monochrome.png"
  web:
    generate: true
    image_path: "assets/icon.png"
  windows:
    generate: true
    image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
